apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-python
spec:
 replicas: 5
 selector:
   matchLabels:
    app: python
 template:
  metadata:
   labels:
     app: python
  spec: 
   containers:
   - name: python
     image: 192.168.1.110:5000/python:0.0.2
     ports:
     - containerPort: 80
     resources:
      requests:
       memory: 32Mi
       cpu: 5m
      limit:
       memory: 64Mi
       cpu: 10m
 strategy:
  canary:
    steps:
    - setWeight: 10
    - pause:
       duration: 2m
    - setWeight: 50
    - pause: {}
