apiVersion: v1
kind: Service
metadata:
  name: service-python-rollout
  labels:
    app: python
spec:
  type: NodePort
  selector:
      app: python
  ports:
  - protocol: TCP
    name: web
    port: 80
    targetPort: 80
